chrome_1 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver"
chrome_2 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 2"
chrome_3 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 3"
chrome_4 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 4"
chrome_5 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 5"
chrome_6 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 6"
chrome_7 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 7"
chrome_8 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 8"
chrome_9 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 9"
chrome_10 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 10"
chrome_11 = "/Users/brucehuynh/Documents/Code_Projects/Daily_Work/Daily_Promotion/source/chromedriver copy 11"


apple_products=['iPhone 15 Pro Max 256GB',
                'iPhone 15 Pro Max 512GB',
                'iPhone 15 Pro 128GB',
                'iPhone 15 Pro 256GB',
                'iPhone 15 Plus 128GB',
                'iPhone 15 Plus 256GB',
                'iPhone 15 128GB',
                'iPhone 15 256GB',
                'iPhone 14 Pro Max 128GB',
                'iPhone 14 Pro Max 256GB',
                'iPhone 14 Pro 128GB',
                'iPhone 14 Pro 256GB',
                'iPhone 14 Plus 128GB',
                'iPhone 14 Plus 256GB',
                'iPhone 14 128GB',
                'iPhone 14 256GB',
                'iPhone 13 128GB',
                'iPhone 13 256GB',
                'iPhone 12 64GB',
                'iPhone 12 128GB',
                'iPhone 11 64GB',
                'iPhone 11 128GB',
                'iPhone SE 2022 64GB',
                'iPhone SE 2022 128GB',
                'iPad Pro 13 inch M4 2024 Wifi + Cellular 256GB',
                'iPad Pro 13 inch M4 2024 Wifi 256GB',
                'iPad Pro 11 inch M4 2024 Wifi + Cellular 256GB',
                'iPad Pro 11 inch M4 2024 Wifi 256GB',
                'iPad Pro 12.9 2022 M2 WiFi 5G 128GB',
                'iPad Pro 12.9 2022 M2 WiFi 5G 256GB',
                'iPad Pro 12.9 2022 M2 WiFi 128GB',
                'iPad Pro 12.9 2022 M2 WiFi 256GB',
                'iPad Pro 11 2022 M2 WiFi 5G 128GB',
                'iPad Pro 11 2022 M2 WiFi 5G 256GB',
                'iPad Pro 11 2022 M2 WiFi 128GB',
                'iPad Pro 11 2022 M2 WiFi 256GB',
                'iPad Air 13 inch M2 2024 Wifi + Cellular 128GB',
                'iPad Air 13 inch M2 2024 Wifi + Cellular 256GB',
                'iPad Air 13 inch M2 2024 Wifi 128GB',
                'iPad Air 13 inch M2 2024 Wifi 256GB',
                'iPad Air 11 inch M2 2024 Wifi + Cellular 128GB',
                'iPad Air 11 inch M2 2024 Wifi + Cellular 256GB',
                'iPad Air 11 inch M2 2024 Wifi 128GB',
                'iPad Air 11 inch M2 2024 Wifi 256GB',
                'iPad Air 5 2022 10.9 inch M1 WiFi 5G 64GB',
                'iPad Air 5 2022 10.9 inch M1 WiFi 5G 256GB',
                'iPad Air 5 2022 10.9 inch M1 WiFi 64GB',
                'iPad Air 5 2022 10.9 inch M1 WiFi 256GB',
                'iPad Gen 10 2022 10.9 inch WiFi 5G 64GB',
                'iPad Gen 10 2022 10.9 inch WiFi 5G 256GB',
                'iPad Gen 10 2022 10.9 inch WiFi 64GB',
                'iPad Gen 10 2022 10.9 inch WiFi 256GB',
                'iPad 10.2 2021 WiFi + Cellular 64GB',
                'iPad 10.2 2021 WiFi + Cellular 256GB',
                'iPad 10.2 2021 WiFi 64GB',
                'iPad 10.2 2021 WiFi 256GB',
                'iPad mini 8.3 2021 WiFi 5G 64GB',
                'iPad mini 8.3 2021 WiFi 5G 256GB',
                'iPad mini 8.3 2021 WiFi 64GB',
                'iPad mini 8.3 2021 WiFi 256GB',
                'MacBook Pro 14 2023 M3 8 CPU/10 GPU/8GB/512GB',
                'MacBook Pro 14 2023 M3 Pro 11 CPU/14 GPU/18GB/512GB',
                'MacBook Pro 16 2023 M3 Pro 12 CPU/18 GPU/18GB/512GB',
                'MacBook Pro 16" 2021 M1 Pro 512GB',
                'MacBook Pro 14 2023 M2 Pro 10CPU 16GPU 16GB/512GB',
                'MacBook Pro 14" 2021 M1 Pro 512GB',
                'MacBook Pro M2 2022 13 inch 8CPU 10GPU 8GB 256GB',
                'Macbook Air M3 15 2024 8CPU 10GPU/8GB/256GB',
                'Macbook Air M3 15 2024 8CPU 10GPU/8GB/512GB',
                'Macbook Air M3 13 2024 8CPU 8GPU/8GB/256GB',
                'Macbook Air M3 13 2024 8CPU 10GPU/8GB/512GB',
                'MacBook Air 15 inch M2 2023 8CPU 10GPU 8GB/256GB',
                'MacBook Air M2 2022 13 inch 8CPU 8GPU 8GB 256GB',
                'MacBook Air 13" 2020 M1 256GB',
                'MacBook Air 13" 2020 M1 512GB',
                'Apple Watch Ultra 2 49mm viền Titanium Dây Ocean Band',
                'Apple Watch Series 9 GPS + Cellular 45mm Viền nhôm Dây cao su cỡ S/M',
                'Apple Watch Series 9 GPS + Cellular 41mm Viền nhôm Dây cao su cỡ S/M',
                'Apple Watch Series 9 GPS 45mm Viền nhôm Dây cao su cỡ S/M',
                'Apple Watch Series 9 GPS 41mm Viền nhôm Dây cao su cỡ S/M',
                'Apple Watch SE 2 GPS + Cellular 44mm viền nhôm dây cao su',
                'Apple Watch SE 2 GPS + Cellular 40mm viền nhôm dây cao su',
                'Apple Watch SE 2 GPS 44mm viền nhôm dây cao su',
                'Apple Watch SE 2 GPS 40mm viền nhôm dây cao su',
                'AirPods Max',
                'AirPods Pro 2023 USB-C',
                'AirPods 3 2021',
                'AirPods 2 hộp sạc dây',
                'AirTag - 4 Pack',
                'AirTag - 1 Pack']


oc_vnpay_dict = {'HH': {0: 'HH', 1: 'HH', 2: 'HH'}, 'Range_Low_HH': {0: 3000000, 1: 20000000, 2: 0},
               'Range_High_HH': {0: 20000000, 1: 200000000, 2: 0}, 'VNPay_Amount_HH': {0: 150000, 1: 150000, 2: 0},
               'Percentage_HH': {0: '1%', 1: '1%', 2: '0'}, 'Date_HH': {0: '2023-8-31', 1: '2023-8-31', 2: '0'},
               'CPS': {0: 'CPS', 1: 'CPS', 2: '0'}, 'Range_Low_CPS': {0: 5000000, 1: 10000000, 2: 17000000},
               'Range_High_CPS': {0: 10000000, 1: 16999999, 2: 200000000},
               'VNPay_Amount_CPS': {0: 100000, 1: 200000, 2: 300000},
               'Date_CPS': {0: '2023-3-31', 1: '2023-3-31', 2: '2023-3-31'}, 'DDV': {0: 'DDV', 1: '0', 2: '0'},
               'VNPay_Percent_DDV': {0: '0,03', 1: '0', 2: '0'}, 'VNPay_Amount_DDV': {0: 300000, 1: 0, 2: 0},
               'Date_DDV': {0: '2022-07-30', 1: '0', 2: '0'}, 'FPT': {0: 'FPT', 1: 'FPT', 2: 'FPT'},
               'Range_Low_FPT': {0: 5000000, 1: 10000000, 2: 30000000},
               'Range_High_FPT': {0: 10000000, 1: 30000000, 2: 200000000},
               'VNPay_Amount_FPT': {0: 50000, 1: 100000, 2: 300000},
               'Date_FPT': {0: '2024-8-31', 1: '2024-8-31', 2: '2024-8-31'}, 'MW': {0: 'MW', 1: 'MW', 2: 'MW'},
               'Range_Low_MW': {0: 4000000, 1: 9000000, 2: 17000000},
               'Range_High_MW': {0: 9000000, 1: 17000000, 2: 200000000},
               'VNPay_Amount_MW': {0: 50000, 1: 100000, 2: 200000},
               'Date_MW': {0: '2024-8-31', 1: '2024-8-31', 2: '2024-8-31'}}

total_links={
    "fpt_urls":
    [
        'https://fptshop.com.vn/dien-thoai/iphone-17-pro-max',
        'https://fptshop.com.vn/dien-thoai/iphone-17',
        'https://fptshop.com.vn/dien-thoai/iphone-air',
        'https://fptshop.com.vn/dien-thoai/iphone-17-pro',
        'https://fptshop.com.vn/dien-thoai/iphone-15',
        'https://fptshop.com.vn/dien-thoai/iphone-14',
        'https://fptshop.com.vn/dien-thoai/iphone-16-pro-max',
        'https://fptshop.com.vn/dien-thoai/iphone-16',
        'https://fptshop.com.vn/dien-thoai/iphone-16-plus',
        'https://fptshop.com.vn/dien-thoai/iphone-16e',
        'https://fptshop.com.vn/dien-thoai/iphone-13',
        'https://fptshop.com.vn/dien-thoai/iphone-16-pro',

        'https://fptshop.com.vn/phu-kien/tai-nghe-airpods-pro-3-2025-usb-c',
        'https://fptshop.com.vn/phu-kien/tai-nghe-airpods-4',
        'https://fptshop.com.vn/phu-kien/tai-nghe-airpods-4-chu-dong-khu-tieng-on',
        'https://fptshop.com.vn/phu-kien/tai-nghe-airpods-pro-2023-usb-c',
        'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-m2-13-2024-8cpu-8gpu-16gb-256gb',
        'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-13-m4-2025-10cpu-8gpu-16gb-256gb',
        'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-15-m4-2025-10cpu-10gpu-16gb-256gb',
        'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-m2-2023-15-inch',
        'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-m3-13-2024-8cpu-8gpu-16gb-256gb',
        'https://fptshop.com.vn/may-tinh-bang/ipad-a16-wifi',
        'https://fptshop.com.vn/may-tinh-bang/ipad-a16-5g',
        'https://fptshop.com.vn/may-tinh-bang/ipad-air-11-inch-m3-2025-wifi',
        'https://fptshop.com.vn/may-tinh-bang/ipad-air-13-inch-m3-2025-wifi',
        'https://fptshop.com.vn/may-tinh-bang/ipad-mini-7-2024-wifi',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-11-gps-46mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-11-gps-42mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-11-gps-cellular-42mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-11-gps-cellular-46mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-10-gps-45mm-vien-nhom-day-cao-su-co-sm',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-10-gps-46mm-vien-nhom-day-cao-su-co-m-l',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-10-gps-cellular-45mm-vien-nhom-day-cao-su-co-sm',
        'https://fptshop.com.vn/smartwatch/apple-watch-series-10-gps-cellular-41mm-vien-nhom-day-cao-su-co-sm',
        'https://fptshop.com.vn/smartwatch/apple-watch-se-3-gps-40mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-se-3-gps-44mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-se-3-gps-cellular-40mm-vien-nhom-day-cao-su',
        'https://fptshop.com.vn/smartwatch/apple-watch-se-3-gps-cellular-44mm-vien-nhom-day-cao-su',
        ]
    ,


    "mw_urls":
    [

    'https://www.thegioididong.com/dtdd/iphone-17-pro-max',
    'https://www.thegioididong.com/dtdd/iphone-17-pro',
    'https://www.thegioididong.com/dtdd/iphone-air',
    'https://www.thegioididong.com/dtdd/iphone-17',
    'https://www.thegioididong.com/dtdd/iphone-16-pro-max',
    'https://www.thegioididong.com/dtdd/iphone-16',
    'https://www.thegioididong.com/dtdd/iphone-16e',
    'https://www.thegioididong.com/dtdd/iphone-15',
    'https://www.thegioididong.com/dtdd/iphone-15-plus',
    'https://www.thegioididong.com/dtdd/iphone-13',
    'https://www.thegioididong.com/dtdd/iphone-14',
    'https://www.thegioididong.com/dtdd/iphone-16-plus',
    'https://www.thegioididong.com/dtdd/iphone-16-pro',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-42mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-46mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-42mm-vien-titanium-day-milan',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-42mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-46mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-42m-vien-titanium-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-46mm-vien-titanium-day-milan',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-11-gps-cellular-46mm-vien-titanium-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-ultra-3-gps-cellular-49mm-vien-titanium-day-ocean',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-ultra-3-gps-cellular-49mm-vien-titanium-day-milan',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-ultra-3-gps-cellular-49mm-vien-titanium-day-alpine',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-ultra-3-gps-cellular-49mm-vien-titanium-day-trail',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-3-40mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-3-gps-cellular-40mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-3-44mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-3-gps-cellular-44mm-vien-nhom-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-s10-lte-46mm-vien-titanium-day-thep',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-10-42mm-day-vai',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-10-46mm-day-vai',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-10-lte-42mm-day-vai',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-series-10-lte-46mm-day-vai',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-s10-lte-46mm-vien-titanium-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-s10-lte-46mm',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-s10-lte-42mm-vien-titanium-day-the-thao',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-2-40mm-vien-nhom-day-silicone',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-2-44mm-vien-nhom-day-silicone',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-2-44mm-vien-nhom-day-vai',
    'https://www.thegioididong.com/dong-ho-thong-minh/apple-watch-se-2-2023-lte-40mm-vien-nhom-day-vai',
    'https://www.thegioididong.com/laptop/macbook-air-13-inch-m4-16gb-256gb',
    'https://www.thegioididong.com/laptop/apple-macbook-air-m2-2022-16gb-256gb',
    'https://www.thegioididong.com/laptop/macbook-air-13-inch-m4-16gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-air-15-inch-m4-16gb-256gb',
    'https://www.thegioididong.com/laptop/macbook-air-15-inch-m4-16gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-air-13-inch-m4-16gb-256gb-sac-70w',
    'https://www.thegioididong.com/laptop/macbook-air-13-inch-m4-24gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-air-15-inch-m4-24gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-air-13-inch-m4-32gb-256gb',
    'https://www.thegioididong.com/laptop/macbook-pro-14-inch-m4-pro-24gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-pro-14-nano-m4-pro-24-512',
    'https://www.thegioididong.com/laptop/macbook-pro-16-inch-m4-pro-24gb-512gb',
    'https://www.thegioididong.com/laptop/macbook-pro-14-inch-m4-pro-48gb-1tb',
    'https://www.thegioididong.com/laptop/macbook-pro-14-inch-m4-pro-24gb-1tb',
    'https://www.thegioididong.com/laptop/macbook-pro-14-inch-m4-pro-48gb-512gb',

    ]
    ,
    "hh_urls":
    [
        'https://hoanghamobile.com/dien-thoai/iphone-17-pro-max',
        'https://hoanghamobile.com/dien-thoai/iphone-air',
        'https://hoanghamobile.com/dien-thoai/iphone-17',
        'https://hoanghamobile.com/dien-thoai/iphone-17-pro'
        ]
    ,

    "ddv_urls":
    [

     ]
    ,

    "vt_urls":
    [
        'https://viettelstore.vn/dien-thoai/iphone-17-256gb-pid355077.html',
        'https://viettelstore.vn/dien-thoai/iphone-17-pro-max-pid355086.html',
        'https://viettelstore.vn/dien-thoai/iphone-17-pro-pid355082.html',
        'https://viettelstore.vn/dien-thoai/iphone-air-pid355092.html',
        'https://viettelstore.vn/dien-thoai/iphone-16-pro-pid339623.html',
        'https://viettelstore.vn/dien-thoai/iphone-16-pro-max-pid339630.html',
        'https://viettelstore.vn/dien-thoai/iphone-16-plus-pid339618.html',
        'https://viettelstore.vn/dien-thoai/iphone-16-128gb-pid339614.html',
        'https://viettelstore.vn/dien-thoai/iphone-16-plus-256gb-pid339619.html',
        'https://viettelstore.vn/dien-thoai/iphone-14-128gb-pid293821.html',
        'https://viettelstore.vn/dien-thoai/iphone-16e-pid347205.html',
        'https://viettelstore.vn/dien-thoai/iphone-16e-256gb-pid347207.html',
        'https://viettelstore.vn/dien-thoai/iphone-13-128gb-pid288660.html',
        'https://viettelstore.vn/dien-thoai/iphone-15-128gb-pid317053.html',

        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-nhom-gps-46mm-day-cao-su-m-l-pid355604.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-nhom-gps-42mm-day-cao-su-s-m-pid355620.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-titan-cellular-46mm-day-milanese-m-l-pid355607.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-titan-cellular-42mm-day-milanese-pid355594.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-titan-cellular-46mm-day-cao-su-m-l-pid355606.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-titan-cellular-46mm-day-cao-su-s-m-pid355598.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-titan-cellular-42mm-day-cao-su-s-m-pid355602.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-nhom-cellular-46mm-day-cao-su-m-l-pid355589.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-nhom-cellular-46mm-day-cao-su-s-m-pid355590.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-series-11-vien-nhom-cellular-42mm-day-cao-su-s-m-pid355600.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-milanese-m-l-pid355588.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-milanese-s-m-pid355603.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-quan-trail-m-l-pid355591.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-quan-trail-s-m-pid355601.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-quan-alpine-s-m-pid355605.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-ultra-3-vien-titan-cellular-49mm-day-quan-alpine-m-l-pid355596.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-gps-40mm-day-cao-su-s-m-pid355618.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-cellular-40mm-day-cao-su-s-m-pid355613.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-gps-44mm-day-cao-su-s-m-pid355615.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-gps-44mm-day-cao-su-s-m-pid355616.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-cellular-44mm-day-cao-su-s-m-pid355617.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-3-vien-nhom-cellular-44mm-day-cao-su-m-l-pid355614.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-gps-40mm-sport-loop-pid347391.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-gps-40mm-sport-band-s-m-pid347390.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-gps-44mm-sport-band-s-m-pid347392.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-gps-44mm-sport-loop-pid347393.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-cellular-40mm-sport-loop-pid347395.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-cellular-40mm-sport-band-s-m-pid347394.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-cellular-44mm-sport-band-s-m-pid347396.html',
        'https://viettelstore.vn/dong-ho-thong-minh/apple-watch-se-2-cellular-44mm-sport-loop-pid347397.html',
        'https://viettelstore.vn/may-tinh-bang/ipad-a16-11-inch-wifi-128gb-pid347940.html',
        'https://viettelstore.vn/may-tinh-bang/ipad-air-m3-11-inch-wifi-128gb-pid347926.html',
        'https://viettelstore.vn/may-tinh-bang/ipad-air-m3-13-inch-wifi-128gb-pid347934.html',
        'https://viettelstore.vn/tai-nghe/airpods-pro-3-pid355611.html',
        'https://viettelstore.vn/tai-nghe/tai-nghe-airpods-4-pid340125.html',
        'https://viettelstore.vn/tai-nghe/airpods-pro-gen-2-usb-c-pid323428.html',
        'https://viettelstore.vn/tai-nghe/tai-nghe-airpods-4-khu-on-chu-dong-pid340124.html'
     ]
    ,

    "cps_urls":
    [
        # 'https://cellphones.com.vn/iphone-13.html',
        # 'https://cellphones.com.vn/iphone-14.html',
        # 'https://cellphones.com.vn/iphone-15.html',
        # 'https://cellphones.com.vn/iphone-16e.html',
        # 'https://cellphones.com.vn/iphone-16.html',
        # 'https://cellphones.com.vn/iphone-16-plus.html',
        # 'https://cellphones.com.vn/iphone-16-pro-256gb.html',
        # 'https://cellphones.com.vn/iphone-16-pro-max.html',
        # 'https://cellphones.com.vn/iphone-air-256gb.html',
        # 'https://cellphones.com.vn/iphone-17-256gb.html',
        # 'https://cellphones.com.vn/iphone-17-pro-max.html',

        'https://cellphones.com.vn/ipad-a16-11-inch.html',
        'https://cellphones.com.vn/apple-ipad-air-m3.html',
        'https://cellphones.com.vn/ipad-mini-7.html',
        'https://cellphones.com.vn/ipad-air-m3-11-inch-256gb.html',
        'https://cellphones.com.vn/ipad-a16-11-inch-5g.html',

        'https://cellphones.com.vn/macbook-air-m2-2022-16gb.html',
        'https://cellphones.com.vn/apple-macbook-air-13-m4-10cpu-8gpu-16gb-256gb-2025.html',
        'https://cellphones.com.vn/apple-macbook-air-13-m4-10cpu-10gpu-16gb-512gb-2025.html',
        'https://cellphones.com.vn/apple-macbook-air-13-m4-10cpu-10gpu-16gb-512gb-2025-sac-70w.html',

        'https://cellphones.com.vn/apple-watch-series-11-46mm.html',
        'https://cellphones.com.vn/apple-watch-series-11-42mm.html',
        'https://cellphones.com.vn/apple-watch-series-10-42mm.html',
        'https://cellphones.com.vn/apple-watch-series-10-42mm-vien-nhom-day-vai.html',
        'https://cellphones.com.vn/apple-watch-ultra-3-49mm-5g.html',
        'https://cellphones.com.vn/apple-watch-se-3-40mm.html',
        'https://cellphones.com.vn/apple-watch-se-3-44mm.html',

        'https://cellphones.com.vn/apple-airpods-4.html',
        'https://cellphones.com.vn/apple-airpods-pro-3.html',
        'https://cellphones.com.vn/apple-airpods-4-chong-on-chu-dong.html',
        'https://cellphones.com.vn/apple-airpods-pro-2-usb-c.html',
        ],

    "tz_urls":
    [
     'https://www.topzone.vn/mac/apple-macbook-air-m2-2023',
     'https://www.topzone.vn/apple-watch/apple-watch-s9-lte-41mm-vien-nhom-day-silicone',
     'https://www.topzone.vn/iphone/iphone-15-plus-256gb',
     'https://www.topzone.vn/ipad/ipad-mini-6-cellular-64gb',
     'https://www.topzone.vn/ipad/ipad-9-wifi-cellular-256gb',
     'https://www.topzone.vn/airtag/thiet-bi-dinh-vi-thong-minh-airtag-1-pack-mx532',
     'https://www.topzone.vn/tai-nghe/tai-nghe-bluetooth-airpods-pro-gen-2-magsafe-charge-usb-c-apple-mtjv3',
     'https://www.topzone.vn/iphone/iphone-11-128gb',
     'https://www.topzone.vn/iphone/iphone-14',
     'https://www.topzone.vn/ipad/ipad-pro-m2-12-9-inch',
     'https://www.topzone.vn/mac/macbook-pro-14-inch-m3-2023',
     'https://www.topzone.vn/apple-watch/apple-watch-series-9-gps-cellular-45mm-sport-band-size-s',
     'https://www.topzone.vn/mac/apple-macbook-pro-13-inch-m2-2022',
     'https://www.topzone.vn/mac/apple-macbook-pro-16-inch-m3-pro-2023-12-core',
     'https://www.topzone.vn/ipad/ipad-pro-m4-11-inch-wifi-256gb',
     'https://www.topzone.vn/iphone/iphone-13',
     'https://www.topzone.vn/apple-watch/apple-watch-se-2022-44mm-vien-nhom',
     'https://www.topzone.vn/ipad/ipad-mini-6',
     'https://www.topzone.vn/iphone/iphone-14-plus-256gb',
     'https://www.topzone.vn/iphone/iphone-14-pro-256gb',
     'https://www.topzone.vn/ipad/ipad-pro-m2-129-wifi-cellular-128gb',
     'https://www.topzone.vn/apple-watch/apple-watch-ultra-2-lte-49mm-vien-titanium-day-ocean',
     'https://www.topzone.vn/ipad/ipad-gen-10',
     'https://www.topzone.vn/mac/macbook-air-15-inch-m3-2024',
     'https://www.topzone.vn/iphone/iphone-14-plus',
     'https://www.topzone.vn/mac/apple-pro-16-m1-pro-2021-10-core-cpu',
     'https://www.topzone.vn/ipad/ipad-air-m2-11-inch-wifi-cellular-128gb',
     'https://www.topzone.vn/ipad/ipad-pro-m4-13-inch-wifi-256gb',
     'https://www.topzone.vn/mac/macbook-air-13-inch-m3-2024-512gb',
     'https://www.topzone.vn/mac/apple-macbook-air-2020-mgn63saa',
     'https://www.topzone.vn/airtag/thiet-bi-dinh-vi-thong-minh-airtag-4-pack-mx542',
     'https://www.topzone.vn/ipad/ipad-pro-m2-11-wifi-256gb',
     'https://www.topzone.vn/ipad/ipad-10-wifi-cellular-64gb',
     'https://www.topzone.vn/iphone/iphone-14-256gb',
     'https://www.topzone.vn/ipad/ipad-pro-m2-11-inch',
     'https://www.topzone.vn/ipad/ipad-air-5-m1-wifi-256gb',
     'https://www.topzone.vn/mac/macbook-air-m2-2022-8-core-gpu',
     'https://www.topzone.vn/apple-watch/apple-watch-s8-lte-45mm',
     'https://www.topzone.vn/mac/apple-macbook-pro-2020-m1-myd82saa',
     'https://www.topzone.vn/ipad/ipad-pro-m2-129-wifi-cellular-256gb',
     'https://www.topzone.vn/iphone/iphone-12-128gb',
     'https://www.topzone.vn/iphone/iphone-15',
     'https://www.topzone.vn/ipad/ipad-air-5-m1-wifi-cellular-64gb',
     'https://www.topzone.vn/ipad/ipad-air-m2-13-inch-wifi-cellular-256gb',
     'https://www.topzone.vn/iphone/iphone-se-2022',
     'https://www.topzone.vn/apple-watch/apple-watch-s9-41mm-vien-nhom-day-silicone',
     'https://www.topzone.vn/iphone/iphone-15-pro-max-512gb',
     'https://www.topzone.vn/ipad/ipad-pro-m2-11-wifi-cellular-128gb',
     'https://www.topzone.vn/ipad/ipad-air-m2-11-inch-wifi-cellular-256gb',
     'https://www.topzone.vn/am-thanh/tai-nghe-bluetooth-airpods-2-apple-mv7n2-trang',
     'https://www.topzone.vn/mac/macbook-air-13-inch-m3-2024',
     'https://www.topzone.vn/apple-watch/apple-watch-s8',
     'https://www.topzone.vn/iphone/iphone-15-pro',
     'https://www.topzone.vn/apple-watch/apple-watch-se-2022',
     'https://www.topzone.vn/iphone/iphone-14-pro-max-256gb',
     'https://www.topzone.vn/iphone/iphone-15-pro-max',
     'https://www.topzone.vn/apple-watch/apple-watch-se-2022-lte-40mm',
     'https://www.topzone.vn/ipad/ipad-10-wifi-cellular-256gb',
     'https://www.topzone.vn/ipad/ipad-gen-9',
     'https://www.topzone.vn/iphone/iphone-14-pro',
     'https://www.topzone.vn/tai-nghe/airpods-pro-2',
     'https://www.topzone.vn/iphone/iphone-se-128gb-2022',
     'https://www.topzone.vn/mac/macbook-air-15-inch-m3-2024-512gb',
     'https://www.topzone.vn/tai-nghe/bluetooth-airpods-max-apple',
     'https://www.topzone.vn/iphone/iphone-15-pro-256gb',
     'https://www.topzone.vn/iphone/iphone-11',
     'https://www.topzone.vn/ipad/ipad-air-m2-13-inch-wifi-256gb',
     'https://www.topzone.vn/ipad/ipad-air-m2-13-inch-wifi-cellular-128gb',
     'https://www.topzone.vn/tai-nghe/airpods-3',
     'https://www.topzone.vn/iphone/iphone-14-pro-max',
     'https://www.topzone.vn/apple-watch/apple-watch-s8-41mm',
     'https://www.topzone.vn/iphone/iphone-15-256gb',
     'https://www.topzone.vn/mac/apple-macbook-air-2020-m1-mgn73saa',
     'https://www.topzone.vn/ipad/ipad-10',
     'https://www.topzone.vn/ipad/ipad-9-wifi-cellular-64gb',
     'https://www.topzone.vn/ipad/ipad-pro-m4-11-inch-wifi-cellular-256gb',
     'https://www.topzone.vn/ipad/ipad-air-m2-11-inch-wifi-128gb',
     'https://www.topzone.vn/ipad/ipad-air-5',
     'https://www.topzone.vn/apple-watch/apple-watch-s8-lte-41mm',
     'https://www.topzone.vn/ipad/ipad-air-5-m1-wifi-cellular-256gb',
     'https://www.topzone.vn/iphone/iphone-15-plus',
     'https://www.topzone.vn/ipad/ipad-mini-6-wifi-256gb',
     'https://www.topzone.vn/mac/macbook-pro-14-inch-m2-pro',
     'https://www.topzone.vn/ipad/ipad-air-m2-13-inch-wifi-128gb',
     'https://www.topzone.vn/apple-watch/apple-watch-series-9-gps-45mm-sport-band-size-s',
     'https://www.topzone.vn/iphone/iphone-12',
     'https://www.topzone.vn/iphone/iphone-13-256gb',
     'https://www.topzone.vn/apple-watch/apple-watch-se-2022-lte-44mm',
     'https://www.topzone.vn/ipad/ipad-air-m2-11-inch-wifi-256gb',
     'https://www.topzone.vn/ipad/ipad-9-wifi-256gb',
     'https://www.topzone.vn/ipad/ipad-pro-m4-13-inch-wifi-cellular-256gb',
     'https://www.topzone.vn/ipad/ipad-pro-m2-129-wifi-256gb']
    ,

    "sd_urls":
    [
"https://shopdunk.com/iphone-15-pro-max",
"https://shopdunk.com/iphone-15-pro-max-512gb",
"https://shopdunk.com/iphone-15-pro-max-1tb",
"https://shopdunk.com/iphone-15-pro",
"https://shopdunk.com/iphone-15-pro-256gb",
"https://shopdunk.com/iphone-15-pro-512gb",
"https://shopdunk.com/iphone-15-pro-1tb",
"https://shopdunk.com/iphone-15-plus",
"https://shopdunk.com/iphone-15-plus-256gb",
"https://shopdunk.com/iphone-15-plus-512gb",
"https://shopdunk.com/iphone-15-128gb",
"https://shopdunk.com/iphone-15-256gb",
"https://shopdunk.com/iphone-15-512gb",
"https://shopdunk.com/iphone-14-pro-max",
"https://shopdunk.com/iphone-14-pro-max-256gb",
"https://shopdunk.com/iphone-14-pro-max-512gb",
"https://shopdunk.com/iphone-14-pro-max-1tb",
"https://shopdunk.com/iphone-14-pro",
"https://shopdunk.com/iphone-14-pro-256gb",
"https://shopdunk.com/iphone-14-pro-512gb",
"https://shopdunk.com/iphone-14-pro-1tb",
"https://shopdunk.com/iphone-14-plus-128gb",
"https://shopdunk.com/iphone-14-plus-256gb",
"https://shopdunk.com/iphone-14-plus-512gb",
"https://shopdunk.com/iphone-14-128gb",
"https://shopdunk.com/iphone-14-256gb",
"https://shopdunk.com/iphone-14-512gb",

"https://shopdunk.com/macbook-pro-14-inch-m3-2023",
"https://shopdunk.com/macbook-pro-14-inch-m3-2023-8gb-ram-1tb-ssd",
"https://shopdunk.com/macbook-pro-14-inch-m3-pro-2023-18gb-ram-512gb-ssd",
"https://shopdunk.com/macbook-pro-14-inch-m3-pro-2023-18gb-ram-1tb-ssd",
"https://shopdunk.com/macbook-pro-14-inch-m3-2023-8gb-ram-512gb-ssd-2",

"https://shopdunk.com/macbook-pro-16-inch-m2-pro-19-core-16gb-512gb",
"https://shopdunk.com/macbook-pro-16-inch-m2-pro-19-core-16gb-1tb",
"https://shopdunk.com/macbook-pro-14-m2-pro-16gb-512gb",
"https://shopdunk.com/macbook-pro-14-m2-pro-16gb-1tb",
"https://shopdunk.com/macbook-air-m3-15-inch",
"https://shopdunk.com/macbook-air-m3-13-inch",
"https://shopdunk.com/apple-watch-ultra-2-lte-49mm-ocean-band",
"https://shopdunk.com/apple-watch-series-8-41mm-nhom-gps-cellular",
"https://shopdunk.com/apple-watch-series-8-45mm-nhom-gps-cellular",
"https://shopdunk.com/apple-watch-series-8-45mm",

"https://shopdunk.com/apple-watch-ultra-2-lte-49mm-ocean-band",
"https://shopdunk.com/apple-watch-series-9-nhom-gps-41mm/",
"https://shopdunk.com/apple-watch-series-9-nhom-gps-45mm-day-cao-su",
"https://shopdunk.com/apple-watch-series-9-nhom-gps-cellular-41mm-sport-band",

"https://shopdunk.com/apple-watch-series-9-nhom-gps-cellular-45mm-sport-band",
"https://shopdunk.com/apple-watch-se-2023-gps-sport-band-s-m",
"https://shopdunk.com/apple-watch-se-2023-gps-sport-band-size-m-l",
"https://shopdunk.com/apple-watch-se-2023-gps-cellular-sport-band-size-sm",
"https://shopdunk.com/apple-watch-se-2023-gps-cellular-sport-band-size-ml",
"https://shopdunk.com/airpods-pro-2-usb-c-2023",
"https://shopdunk.com/airpods-pro-2",

'https://shopdunk.com/ipad-air-m2-11-inch-wi-fi',
'https://shopdunk.com/ipad-air-m2-11-inch-wi-fi-256gb',
'https://shopdunk.com/ipad-air-m2-11-inch-wi-fi-cellular',
'https://shopdunk.com/ipad-air-m2-11-inch-wi-fi-cellular-256gb',
'https://shopdunk.com/ipad-air-m2-13-inch-wi-fi',
'https://shopdunk.com/ipad-air-m2-13-inch-wi-fi-256gb',
'https://shopdunk.com/ipad-air-m2-13-inch-wi-fi-cellular',
'https://shopdunk.com/ipad-air-m2-13-inch-wi-fi-cellular-256gb',

'https://shopdunk.com/ipad-pro-m4-11-inch-wi-fi',
'https://shopdunk.com/ipad-pro-m4-11-inch-wi-fi-512gb',
'https://shopdunk.com/ipad-pro-m4-11-inch-wi-fi-cellular',
'https://shopdunk.com/ipad-pro-m4-11-inch-wi-fi-cellular-512gb',
'https://shopdunk.com/ipad-pro-m4-13-inch-wi-fi',
'https://shopdunk.com/ipad-pro-m4-13-inch-wi-fi-512gb',
'https://shopdunk.com/ipad-pro-m4-13-inch-wi-fi-cellular',
'https://shopdunk.com/ipad-pro-m4-13-inch-wi-fi-cellular-512gb',

'https://shopdunk.com/ipad-pro-m2-128gb',
'https://shopdunk.com/ipad-pro-m2-129-inch-wifi-256gb',
"https://shopdunk.com/ipad-pro-m2-12-9-inch-wifi-cellular-128gb",
"https://shopdunk.com/ipad-pro-m2-12-9-inch-wifi-cellular-256gb",
"https://shopdunk.com/ipad-pro-m2-11-inch-wifi-128gb",
"https://shopdunk.com/ipad-pro-m2-11-inch-wifi-256gb",
"https://shopdunk.com/ipad-pro-m2-11-inch-wifi-cellular-256gb",
"https://shopdunk.com/ipad-gen-10-10-9-inch-wi-fi-64gb",
"https://shopdunk.com/ipad-gen-10-10-9-inch-wi-fi-256gb",
"https://shopdunk.com/ipad-gen-10-10-9-inch-wi-fi-cellular-64gb",
"https://shopdunk.com/ipad-gen-10-10-9-inch-wi-fi-cellular-256gb",
"https://shopdunk.com/iphone-13",
"https://shopdunk.com/iphone-13-256-gb",
"https://shopdunk.com/iphone-13-512-gb",
"https://shopdunk.com/iphone-12-64gb",
"https://shopdunk.com/iphone-12-128gb",
"https://shopdunk.com/iphone-11/",
"https://shopdunk.com/iphone-11-128gb",
"https://shopdunk.com/iphone-se-2022",
"https://shopdunk.com/ipad-air-5",
"https://shopdunk.com/ipad-air-5-wifi-256gb",
"https://shopdunk.com/ipad-air-5-wifi-cellular-64gb",
"https://shopdunk.com/ipad-air-5-wifi-cellular-256gb",
"https://shopdunk.com/ipad-gen-9-64gb-wifi",
"https://shopdunk.com/ipad-gen-9-2021-wifi-256gb",
"https://shopdunk.com/ipad-gen-9-2021-wifi-cellular-64gb",
"https://shopdunk.com/ipad-gen-9-2021-wifi-cellular-256gb",
"https://shopdunk.com/ipad-mini-6",
"https://shopdunk.com/ipad-mini-6-256gb",
"https://shopdunk.com/macbook-air-15-inch-m2",
"https://shopdunk.com/macbook-air-15-inch-m2-8gb-ram-512gb-ssd",
"https://shopdunk.com/macbook-air-m1-2020",
"https://shopdunk.com/macbook-air-m2-2022",
"https://shopdunk.com/macbook-air-m2-2022-8gb-512gb",
"https://shopdunk.com/macbook-pro-m2-2022",
"https://shopdunk.com/macbook-pro-13-inch-m2-2022-10-core-8gb-ram-512gb-ssd",
"https://shopdunk.com/apple-watch-series-3-nhom",
"https://shopdunk.com/airpods-max/",
"https://shopdunk.com/airpods-pro-2021/",
"https://shopdunk.com/airpods-gen-3/",
"https://shopdunk.com/airpods-2/",
"https://shopdunk.com/apple-airtag-1-pack"
]

}
